export const Questions = [
    {
      prompt: "What is legal age to vote in India?",
      optionA: "15",
      optionB: "20",
      optionC: "25",
      optionD: "18",
      asnwer: "optionD",
    },
    {
      prompt: "Who is known as father of Constitiution?",
      optionA: "Mohammad Saadulla",
      optionB: "Jawaharlal Nehru",
      optionC: "Dr Bhimrao Ambedkar ",
      optionD: "Sardar Vallabhbhai Patel",
      asnwer: "optionC",
    },
    {
      prompt: "Which of the following is a fundamental right guaranteed by the Indian Constitution?",
      optionA: "Right to Privacy",
      optionB: "Right to Enterntainment",
      optionC: "Right to Luxury",
      optionD: "Right to Silence",
      asnwer: "optionA",
    },
    {
    prompt: "Which branch of government is responsible for making laws?",
    optionA: "Executive",
    optionB: "Judicial",
    optionC: "Legislative",
    optionD: "Administrative",
    asnwer: "optionC",
    },
    {
    prompt: "At what age can individuals typically vote in many democratic elections?",
    optionA: "16",
    optionB: "18",
    optionC: "21",
    optionD: "25",
    asnwer: "optionB",
    },
    {
    prompt: "What is the purpose of a will in legal terms?",
    optionA: "To distribute assets after death",
    optionB: "To declare bankruptcy",
    optionC: "To file for divorce",
    optionD: "To create a business partnership",
    asnwer: "optionA",
    },
    {
    prompt: "What is the age at which a person is generally considered legally responsible for their actions in criminal court?",
    optionA: "12",
    optionB: "16",
    optionC: "18",
    optionD: "21",
    asnwer: "optionA",
    },
    {
    prompt: "Which article of the Indian Constitution guarantees the Right to Freedom of Speech?",
    optionA: "Article 19",
    optionB: "Article 21",
    optionC: "Article 14",
    optionD: "Article 16",
    asnwer: "optionA",
    },

  ];